version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.13.1
    steps:
    - checkout
    - run:
        name: "install dependencies"
        command: npm install
    - run:
        name: "run lint"
        command: npm run lint
    - run:
        name: "run tests"
        command: npm test

workflows:
  version: 2.1
  test:
    jobs:
      - test